name: Update Mihomo Rules

permissions:
  contents: write


on:

  schedule:
    # 每天北京时间凌晨2点运行
    # UTC 18:00
    - cron: "0 18 * * *"

  workflow_dispatch:


env:

  MIHOMO_VERSION: v1.19.29



jobs:

  update:

    runs-on: ubuntu-latest


    steps:


    - name: Checkout
      uses: actions/checkout@v5



    - name: Download mihomo

      run: |

        wget -O mihomo.gz \
        https://github.com/MetaCubeX/mihomo/releases/download/${MIHOMO_VERSION}/mihomo-linux-amd64-v1-${MIHOMO_VERSION}.gz


        gzip -dc mihomo.gz > mihomocore


        chmod +x mihomocore


        ./mihomocore -v



    - name: Download ChinaMax rules

      run: |

        wget -O ChinaMax_Domain.yaml \
        https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml


        wget -O ChinaMax_IP.yaml \
        https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP.yaml



    - name: Convert Domain rules

      run: |

        mkdir -p mihomo/rule


        ./mihomocore convert-ruleset \
        domain \
        yaml \
        ChinaMax_Domain.yaml \
        mihomo/rule/ChinaMax_Domain.mrs



    - name: Convert IP rules

      run: |

        ./mihomocore convert-ruleset \
        ipcidr \
        yaml \
        ChinaMax_IP.yaml \
        mihomo/rule/ChinaMax_IP.mrs



    - name: Commit changes

      run: |

        git config user.name github-actions

        git config user.email github-actions@github.com


        git add mihomo/rule/


        git diff --cached --quiet && exit 0


        git commit -m "Update ChinaMax MRS"


        git push



    - name: Cleanup

      run: |

        rm -f mihomo.gz

        rm -f mihomocore

        rm -f ChinaMax_Domain.yaml

        rm -f ChinaMax_IP.yaml
